### ISSUE TITLE
Roadmap for October 2015 

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#13]
## Funding
- [Fundraiser October 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201510/) yielded **€176.03** (-38% compared to September).
- There are no extra expenses (domain, hosting, etc.) planned for October 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is 176.03/11 = **16 hours**
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Importance of tasks: Urgent > Code review > Bugs > Features requested by Patrons >> ~~Other feature requests~~ (no time for that)
- Milestone October 2015
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/October%202015)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/October%202015)
### Urgent
- [x] Update Nuvola Player 3 release notes tiliado/nuvolaplayer.project#11 
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128
- [ ] Update Service Integration Guidelines tiliado/nuvolaplayer#127 
- [ ] Create packages for Ubuntu 15.10 Wily Werewolf tiliado/nuvolaplayer#166 - postponed until November 2015
- [ ] Create packages for Fedora 23 tiliado/nuvolaplayer#167 - postponed until November 2015
- [ ] ~~Add translations tiliado/nuvolaplayer#10~~ postponed until 3.1
- [ ] ~~When clicking the play button next to a song on the artist panel, window shifts out tiliado/nuvola-app-spotify#7 - It is necessary to reproduce the issue in the jhbuild of the WebKitGTK and forward it upstream.~~
- [ ] ~~Can't login to Rdio via Facebook tiliado/nuvola-app-rdio#4 - unreproducible~~
- [ ]  ~~Google Play Music is not working in Ubuntu 14.04: freeze in the middle of loading tiliado/nuvolaplayer#134 - javascript error, try in virtualbox, no time for that~~
- [ ] Wrong enabled/disabled state of actions in nuvolaplayer3ctl tiliado/nuvolaplayer#112
- [ ] MPRIS interface doesn't block disabled actions (e.g. play) tiliado/nuvolaplayer#136
- [ ] ~~Google Play Music might not work with Labs Notifications enabled tiliado/nuvolaplayer#150~~
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
### Important

All code reviews of new service integration scripts have been postponed to January 2016
- [ ] ~~Service Request: Youtube tiliado/nuvolaplayer#83 - code review~~
- [ ] ~~Service Request: Microsoft Groove tiliado/nuvolaplayer#149 - code review~~
- [ ] ~~Service request: RuneAudio  tiliado/nuvolaplayer#154  - code review~~
- [ ] ~~Service request: Soundcloud tiliado/nuvolaplayer#30 - code review~~
- [ ] ~~Service Request: Ampache/Owncloud [$25] tiliado/nuvolaplayer#52~~
- [ ] Set default player window width from metadata.json tiliado/nuvolaplayer#141
- [ ]  Apply URL sandbox also for window.open() tiliado/nuvolaplayer#142
- [ ]  ~~Service request: Youradio tiliado/nuvolaplayer#153  - code review~~
- [ ] Create welcome wizard tiliado/nuvolaplayer#18
### Other
- [x]  The player window doesn't follow the dark theme preference tiliado/nuvolaplayer#163
- [ ] Update screenshots and social network artwork tiliado/nuvolaplayer.project#10 
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [x] Change name of MPRIS interface tiliado/nuvolaplayer#120
- [ ] Use jslint for web app scripts tiliado/nuvolaplayer#132 
- [ ] Show donate bar based on 0.5 hour ticks tiliado/nuvolaplayer#122 
- [x] Change name of MPRIS interface tiliado/nuvolaplayer#120
- [ ] Media player extension also says that Google Play "stops" very briefly whenever I skip a song tiliado/nuvolaplayer#118

**Comment by jiri-janousek** [comment]
Donations €109.97 so far + up to $95.12 × 0.9 from Patreon (pending).

**Comment by jiri-janousek** [comment]
Total funding €176.03 (-38%). Funded time 176.03/11 = 16 hours.

**Comment by jiri-janousek** [comment]
All code reviews of new service integration scripts have been postponed to January 2016:

> Hello XXX. I regret to tell you I don't expect to have time for the code review and packaging of your integration script until the release of the stable version of Nuvola Player 3.0, which is due at the end of December 2015. Since the funding of the Nuvola Player project has recently dropped significantly, I cannot spend time on tasks that are not crucial for the stable release. However, the release cycle of web app scripts is not bound to Nuvola Player releases, so I can prepare packages for your script in January 2016 regardless of the development progress and the release date of Nuvola Player 3.1. Thanks for your understanding and patience.

**Comment by jiri-janousek** [comment]
Out of funds, report: https://tiliado.eu/nuvolaplayer/funding/tasks/201510/
