### ISSUE TITLE
Roadmap for November 2015

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#14]
## Funding
- [Fundraiser November 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201511/) yielded **€199.35** (+13% compared to October).
- There are no extra expenses (domain, hosting, etc.) planned for November 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is 199.35/11 = **18 hours**
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone November 2015
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/November%202015)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/November%202015)
- [x] Create packages for Ubuntu 15.10 Wily Werewolf tiliado/nuvolaplayer#166
- [x] Update Service Integration Guidelines tiliado/nuvolaplayer#127
- [x] Wrong enabled/disabled state of actions in nuvolaplayer3ctl tiliado/nuvolaplayer#112
- [x] MPRIS interface doesn't block disabled actions (e.g. play) tiliado/nuvolaplayer#136
- [x] Set default player window width from metadata.json tiliado/nuvolaplayer#141
- [x] Rename Google Play Music repository tiliado/nuvolaplayer#173
- [x] Create packages for Fedora 23 tiliado/nuvolaplayer#167
- [x]  Repository listing is confusing (files without download links, 403 error) tiliado/nuvolaplayer.project#15
- [ ] _Postponed:_Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ] _Postponed:_ Update screenshots and social network artwork tiliado/nuvolaplayer.project#10
- [ ] _Postponed:_ Apply URL sandbox also for window.open() tiliado/nuvolaplayer#142
- [ ] _Postponed:_ Check Diorite logging works correctly with multiple processes tiliado/nuvolaplayer#178
- [ ] _Postponed:_ Use refreshed icon sets for services tiliado/nuvolaplayer#126
- [ ] _Postponed:_ Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
- [ ] _Postponed:_ Create welcome wizard tiliado/nuvolaplayer#18
- [ ] _Postponed:_ Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126

**Comment by jiri-janousek** [comment]
Patreon payout has arrived ($82.00), total funding for November: **€199.35 ~ 18 hours** (+13%)

**Comment by jiri-janousek** [comment]
Out of funds, next month #18

**Comment by jiri-janousek** [comment]
[Report for Patrons](https://tiliado.eu/nuvolaplayer/funding/tasks/201511/)
