### ISSUE TITLE
Roadmap for December 2015

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#18]
**Top goal: release Nuvola Player 3.0 stable**
## Funding
- [Fundraiser December 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201512/) yielded **€161.76** (-19% compared to November).
- There are no extra expenses (domain, hosting, etc.) planned for December 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is 161.76/11 = **14.7 hours**
## Proposed tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone December 2015
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/December%202015)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/December%202015)
### Important
- [x] Enable caret browsing tiliado/nuvolaplayer#188
- [x] Add documentation about desktop launchers tiliado/nuvolaplayer#187
- [x] Nuvola Player resets icon at update tiliado/nuvolaplayer#184
- [x] Remove This is My Jam script  tiliado/nuvola-app-this-is-my-jam#4
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ]  Update screenshots and social network artwork tiliado/nuvolaplayer.project#10
- [x] Check Diorite logging works correctly with multiple processes tiliado/nuvolaplayer#178
- [x] Move generic widgets to Diorite tiliado/nuvolaplayer#111
- [x] Check real size in `string utf8_string(JS.String jsstring)` #110 (GFM: tiliado/nuvolaplayer#110) 
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ]  Spotify icon is broken in GNOME tiliado/nuvolaplayer#180
- [x] Create welcome wizard tiliado/nuvolaplayer#18
### Other
- [ ]  Apply URL sandbox also for window.open() tiliado/nuvolaplayer#142
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
### Backlog
- Forwarded to maintainer: [No MediaKey Control for Spotify WebApp](https://github.com/tiliado/nuvolaplayer/issues/185)
- Forwarded to maintainer: [Amazon Cloud Player: Unity no background play and no integration with indicator](https://github.com/tiliado/nuvola-app-amazon-cloud-player/issues/7)
-  Not working anymore since Amazon updated their player tiliado/nuvola-app-amazon-cloud-player#8

**Comment by jiri-janousek** [comment]
Fundraiser:
- PayPal + Gratipay = €117.34
- Patreon $55 pending

**Comment by jiri-janousek** [comment]
- Funded time is 161.76/11 = **14.7 hours** (-19%)
- Threshold for revenue sharing with contributors wasn't reached :-(

**Comment by jiri-janousek** [comment]
- Nuvola Player 3.0 was released, but only thanks to funds from the January 2015 Fundraiser.
- Out of funds, next month #19
