### ISSUE TITLE
Roadmap for January 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#19]
## Funding
-  [Fundraiser January 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201601/) yielded **€374.79**.
- There are no extra expenses (domain, hosting, etc.) planned for December 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is 374.79/12 = **31.23 hours** wow!
## Proposed tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone January 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/January%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/January%202016)
### Nuvola Player 3.0

**Most of the funded time was used in December to release Nuvola Player 3.0 Stable.** See #18 
### Other
- [x] Notify all developers about new Contributor Guidelines
- [x] Notify all pending code reviews about new Contributor guidelines
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10

**Comment by jiri-janousek** [comment]
- Funded time is  374.79/12 = **31.23 hours** wow!
- Threshold for revenue sharing with contributors wasn't reached :-(
- Most of the funded time was used in December to release Nuvola Player 3.0 Stable. See #18

**Comment by jiri-janousek** [comment]
Done "Notify all developers about new Contributor Guidelines" - I've posted [New Service Integration Guidelines and Format requirements flags](https://groups.google.com/d/msg/nuvola-player-devel/Eec-MkJJ0cA/C-pyEsL4AQAJ).

**Comment by jiri-janousek** [comment]
Out of funds, next month #21

**Comment by jiri-janousek** [comment]
[Nuvola Player in January 2016 - Report for patrons](https://tiliado.eu/nuvolaplayer/funding/tasks/201601/)
