### ISSUE TITLE
Roadmap for February 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#21]
## Funding
-  [Fundraiser February 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201602/) yielded **€307.85**.
- There are no extra expenses (domain, hosting, etc.) planned for February 2016.
- Funded time is 307.85/13 = **23.68 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached :-1: 
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone February 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/February%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/February%202016)
- Pending code reviews:
  - [ ]  Service request: RuneAudio tiliado/nuvolaplayer#154 Sep 04
  - [x]  Service Request: Microsoft Groove tiliado/nuvolaplayer#149 Aug 31
  - [ ]  Service request: Youradio tiliado/nuvolaplayer#153 Sep 04
  - [x] Service request: Soundcloud  tiliado/nuvolaplayer#30
- Or new services:
  - [ ] Service Request: Ampache/Owncloud [$25] tiliado/nuvolaplayer#52
  - [ ]  Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
  - [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
  - [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
  - [ ] Service Request: Goear tiliado/nuvolaplayer#130
- [x] Allow to install integration script independently on debian based distributions tiliado/nuvolaplayer#164
- [ ]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165 
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
- [ ]  Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2

**Comment by jiri-janousek** [comment]
-  [Fundraiser February 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201602/) yielded **€307.85**.
- There are no extra expenses (domain, hosting, etc.) planned for February 2016.
- Funded time is 307.85/13 = **23.68 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached :-1:

**Comment by jiri-janousek** [comment]
Out of funds. Next month #24
