### ISSUE TITLE
Roadmap for Nuvola Player 3.1

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#22]
Rolling releases **Nuvola Player 3.1.x lead to the stable release **Nuvola Player 3.2.0**.

## Milestone 3.1.1 - October 2016
- [x] Option to always run in background
- [x] MPRIS rating - in progress
- [x] Packaging improvements
- [x] Icon sets - pull requests
- [x] Contributing.md - pull requests
- [x] License metadata field - add guidelines & pull requests
- [x] Experimental password manager.
- [x] Experimental: Remote control over HTTP - web & Pebble

## Milestone 3.1.2 - December 2016

- [ ] MPRIS rating - documentation
- [ ] More robust album art download.
- [ ] PulseAudio tweaks
- [ ] Volume management

## Milestone 3.1.3 - February 2016
- [ ] Format requirements  - add guidelines (require 3.1.0) & pull requests
- [ ] HTML 5 Audio - WebKitGTK+ 2.15.2
- [ ] Experimental: Remote control over HTTP - Android
- [ ] Experimental: Remote control over Bluetooth - Android

## Postponed

- [ ] Web App rating
- [ ] Translations
- [ ] Default media player
- [ ] Progress bar

**Comment by jiri-janousek** [comment]
Closing in favour of tiliado/nuvolaplayer#295
