### ISSUE TITLE
Roadmap for March 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#24]
## Funding
- [Fundraiser March 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201603/) yielded **€170.52** .
- There is **one extra expense** (domain, hosting, etc.) planned for March 2016 - **€5.12** for the tiliado.eu domain (tiliado/nuvolaplayer.project#28).
- Funded time is 165.4/14 = **11.81 hours**
- Threshold **40 hours** for revenue sharing with contributors {was/wasn't} reached. 
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone March 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/March%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/March%202016)

**Goal:**  Release 3.1.1  tiliado/nuvolaplayer#209
### Critical
- [x] Renew the tiliado.eu domain tiliado/nuvolaplayer.project#28
### New Services

At least 2 new services each month!
- [ ] Code review: RuneAudio tiliado/nuvolaplayer#154 Sep 04
- [ ] Code review:  Youtube tiliado/nuvolaplayer#83 Aug 31
- [x] Service Request: Ampache/Owncloud [$25] tiliado/nuvolaplayer#52
- [ ] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130
### Started, but not finished yet
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 + Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2
- [ ]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165
- [x]  Spotify icon is broken in GNOME tiliado/nuvolaplayer#180
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
