### ISSUE TITLE
Roadmap for April 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#29]
## Funding

Funding in progress, see [Fundraiser April 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201604/)  for details.
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone April 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/April%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/April%202016)
### Critical
- Use WebKitGTK 2.8.5 for Ubuntu 14.04 packages tiliado/nuvolaplayer#216
- Packages for Ubuntu 16.04 Xenial Xerus tiliado/nuvolaplayer#213
- Add metadata about minimal WebKitGTK version tiliado/nuvolaplayer#215
### Support
- Google Play window showing up empty tiliado/nuvolaplayer#207
- Enormous memory usage in Arch Linux tiliado/nuvolaplayer#200
### New Services

At least 2 new services each month!
- [ ] Code review: RuneAudio tiliado/nuvolaplayer#154 Sep 04
- [ ] Code review:  Youtube tiliado/nuvolaplayer#83 Aug 31
- [ ] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130
### Started, but not finished yet
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 + Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2
- [ ]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
