### ISSUE TITLE
Roadmap for June 2015

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#3]
## Funding
- [June 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201506/) is the first month which spends funds received in the previous month (2 [Gratipay payments](https://gratipay.com/~NuvolaPlayer/) from May 2015) alongside its [Patreon donations](https://www.patreon.com/nuvolaplayer) (to be received in early June). Funds received in June 2015 (except for Patreon donations) will be counted to the fundraiser for July 2015
- Donations received for June 2015: 101 EUR
- **Funded time: 10.1 hours of work**
## Tasks

[List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer), but funded time is pretty low. Considering only urgent or quick tasks:
### Completed Tasks
- [x] Final Google Play Music fix (tiliado/nuvolaplayer#100): A lot of Nuvola Patrons use Google Play Music. :construction_worker: ~~5 hours~~ 7.71 hours
- [x] Can't build using vala 0.28.0 (tiliado/nuvolaplayer#102): Easy to fix, patch available. :construction_worker: ~~15 min~~ 8 min
- [x] Remaining ~~2.5 hours~~ 2.76 hours - user support
### Postponed Tasks
- [ ]  Code review and packaging: TuneIn Radio (tiliado/nuvolaplayer#43) :construction_worker: 1 hour
- [ ] Also scrobble album to last.fm (tiliado/nuvolaplayer#73):  Easy to fix. :construction_worker: 15 min
- [ ] Warn user when global keybinding fails and provide help (tiliado/nuvolaplayer#93): Easy to fix. :construction_worker: 30 min
- [ ] Prepare packages for Debian 9 Stretch (testing) (tiliado/nuvolaplayer#96) :construction_worker: 1 hour if everything goes well, postpone otherwise

**Comment by jiri-janousek** [comment]
Closing, next is #4
