### ISSUE TITLE
Roadmap for May 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#30]
## Funding
- [Fundraiser May 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201605/) yielded **€140.75** .
- €134.75 is remaining after an advance of **€6** on **tiliado.eu domain & hosting**.
- Funded time is 134.75/14 = **8.98 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached. 
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone April 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/April%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/April%202016)
### Critical
- [ ]  Add metadata about minimal WebKitGTK version tiliado/nuvolaplayer#215
- [ ]  Add dependency on libwebkit2gtk-4.0-37-gtk2 tiliado/nuvolaplayer#232 
- [x] symlink scalable icon to proper destination tiliado/nuvola-app-google-play-music#13 - fix also other scripts and the template
### Support
- ~~Enormous memory usage in Arch Linux tiliado/nuvolaplayer#200~~
### New Services

At least one new service each month!
- [ ] Code review:  Youtube tiliado/nuvolaplayer#83 Aug 31
- [ ] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130
### Started, but not finished yet
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 + Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2
- [ ]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
