### ISSUE TITLE
Roadmap for June 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#31]
## Funding

See [Fundraiser June 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201606/) for details.
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone June 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/June%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/June%202016)
#### Packaging
- [ ]  Packages for Arch Linux [$25] tiliado/nuvolaplayer#8 
- [ ] Packages for Fedora 24 tiliado/nuvolaplayer#214 
#### Release 3.0.3
- [x] Disabling notifications generates warnings in log tiliado/nuvolaplayer#227
- [ ] Add metadata about minimal WebKitGTK version tiliado/nuvolaplayer#215
- [ ] Add minimal WebKitGTK version requirement and warning tiliado/nuvola-app-soundcloud#5
- [ ] Spotify cannot connect behind HTTP proxy (Privoxy) in Linux Mint 17.3 tiliado/nuvola-app-spotify#13 
- [x] Release 3.0.3 tiliado/nuvolaplayer#226 
#### Release 3.1.1
- [ ] Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2 - including MPRIS rating
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 - developer documentation
- [x] Examine HTML5 Audio support in Google Play [$15] tiliado/nuvolaplayer#91 - remaining distros, make announcement & user doc
- [ ] Release 3.1.1 tiliado/nuvolaplayer#209 
### New Services

At least one new service each month!
- [ ] Code review:  Youtube tiliado/nuvolaplayer#83
- [ ] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130
#### Update Service Scripts
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126 
- [ ]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165 - license field
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
#### Format Support
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10
#### Old bugs
- [ ]  When clicking the play button next to a song on the artist panel, window shifts out tiliado/nuvola-app-spotify#7

**Comment by jiri-janousek** [comment]
Out of funds.
