### ISSUE TITLE
Roadmap for July 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#32]
## Funding

See [Fundraiser July 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201607/) for details.
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone July 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/July%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/July%202016)
#### Critical
- [x] Packages for Fedora 24 tiliado/nuvolaplayer#214
- [x] Nuvola Player crashes in Wayland session after gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed tiliado/nuvolaplayer#181 
### Feedback
- [x] Packages for Arch Linux [$25] tiliado/nuvolaplayer#8 - provide feedback to Celti
- [x] Examine HTML5 Audio support in Google Play [$15] tiliado/nuvolaplayer#91 - create web page testing codecs, respond to feedback
- [ ] Code review:  Youtube tiliado/nuvolaplayer#83
- [ ] After tiliado/nuvola-app-mixcloud#6 add CONTRIBUTING.md
- [x]  When clicking the play button next to a song on the artist panel, window shifts out tiliado/nuvola-app-spotify#7 
#### Update Service Scripts
- [ ] Update all service integration script to use the latest features tiliado/nuvolaplayer#242
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126 
- [ ]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165 - license field
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
#### WebKitGTK upgrade requests
- [x] Add metadata about minimal WebKitGTK version tiliado/nuvolaplayer#215
- [x] Add minimal WebKitGTK version requirement and warning tiliado/nuvola-app-soundcloud#5
- [ ] Spotify cannot connect behind HTTP proxy (Privoxy) in Linux Mint 17.3 tiliado/nuvola-app-spotify#13 
- [x] Google Play Music - which version is required?
#### Release 3.1.1
- [ ] Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2 - including MPRIS rating
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 - developer documentation
- [ ] Release 3.1.1 tiliado/nuvolaplayer#209 
### New Services
- [ ] Code review:  Youtube tiliado/nuvolaplayer#83
- [ ] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130
#### Format Support
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10
#### Backlog
- [ ]  Let user disable media keys grabbing tiliado/nuvolaplayer#237 
- [ ]  Non-media apps eat global media hotkeys tiliado/nuvolaplayer#230
- [ ]  Code review: Google Keep integration tiliado/nuvolaplayer#222
- [ ] Progress indication while loading the Google Play Music page tiliado/nuvolaplayer#229
- [ ] Document how to get backtrace tiliado/nuvolaplayer#192
- [ ]  Check whether a web app volume slider is synchronized with a PulseAudio stream volume tiliado/nuvolaplayer#139
- [ ] Warn when PulseAudio flat-volumes feature is enabled tiliado/nuvolaplayer#138
