### ISSUE TITLE
Roadmap for August 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#35]
Roadmaps: [July 2016](https://github.com/tiliado/nuvolaplayer.project/issues/32) • **August 2016** • [September 2016](https://github.com/tiliado/nuvolaplayer.project/issues/37)
## Funding
- [Fundraiser August 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201608/) yielded **€145.02**.
- €139.02 remains after an advance of **€6** on **tiliado.eu domain & hosting**.
- Funded time is 139.02/15 = **9.26 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached. 
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone August 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/August%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/August%202016)
### Critical
- [x] Spotify cannot connect behind HTTP proxy (Privoxy) in Linux Mint 17.3 tiliado/nuvola-app-spotify#13 
- [x] Code review:  Youtube tiliado/nuvolaplayer#83
- [ ] Fix all critical warnings tiliado/nuvolaplayer#247
- [ ] Release 3.0.4 tiliado/nuvolaplayer#246
### Update Service Scripts
- [x] Update all service integration script to use the latest features tiliado/nuvolaplayer#242
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126 
- [x]  Some missing information in Ubuntu package metadata tiliado/nuvolaplayer#165 - license field
- [x] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128 - pull requests to repositories
### Pending
- [ ] Packages for Arch Linux [$25] tiliado/nuvolaplayer#8 - wait for a bounce from Celti
### Format Support
- [ ] Examine HTML5 Audio support in Google Play [$15] tiliado/nuvolaplayer#91 - write to the author of MSE WebKit fork
- [ ] Check HTML5 Audio support in streaming services and disable Flash tiliado/nuvolaplayer#158
- [ ] Amazon cloud player doesn't have a debian dependency on flash tiliado/nuvola-app-amazon-cloud-player#10

**Comment by jiri-janousek** [comment]
Out of funds
