### ISSUE TITLE
Roadmap for September 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#37]
Roadmaps: [August 2016](https://github.com/tiliado/nuvolaplayer.project/issues/35) • **September 2016** • [October 2016 ](https://github.com/tiliado/nuvolaplayer.project/issues/39)
## Funding
- [Fundraiser September 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201609/) yielded **199.89**.
- 193.89 remains after an advance of **€6** on **tiliado.eu domain & hosting**.
- Funded time is 193.89/15 = **12.92 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached. 
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Milestone September 2016
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/September%202016)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/September%202016)
### Critical
- [ ] Fix all critical warnings tiliado/nuvolaplayer#247
- [x]  Let user disable media keys grabbing tiliado/nuvolaplayer#237 
- [x] Release 3.0.4 tiliado/nuvolaplayer#246
- [ ] Update all service integration script to use the latest features tiliado/nuvolaplayer#242
- [ ] Use refreshed icon sets for services tiliado/nuvolaplayer#126 
### New Services

If funding gets over 10 hours, let's add at least one new script. [Funding in previous months was low](https://raw.githubusercontent.com/tiliado/nuvolaplayer.project/master/funding/funded_time_2016_06.png).
- [ ] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130

**Comment by jiri-janousek** [comment]
Out of funds.
