### ISSUE TITLE
Roadmap for October 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#39]
Roadmaps: [September 2016](https://github.com/tiliado/nuvolaplayer.project/issues/37) • **October 2016** • [November 2016](https://github.com/tiliado/nuvolaplayer.project/issues/42)

## Funding

- [Fundraiser October 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201610/)  yielded **€171.44**.
- €165.44 remains after an advance of **€6** on **tiliado.eu domain & hosting**.
- Funded time is 165.44/15 = **11.02 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached. 

### Critical
- [x] Packages for Ubuntu 16.10
- [x] Take over the Amazon Cloud Player
- [ ] Fix all critical warnings tiliado/nuvolaplayer#247
- [ ] Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2 - including MPRIS rating
### Watchlist
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 - developer documentation & Is there new release at the GNOME Shell Extensions website?
- [x] Update all service integration script to use the latest features tiliado/nuvolaplayer#242
- [x] Packages for Arch Linux [$25] tiliado/nuvolaplayer#8 - wait for a bounce from Celti

### New Services

If funding gets over 15 hours, let's add at least one new script.
- [x] Service Request: SiriusXM Radio  tiliado/nuvolaplayer#198
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130
### Milestone 3.1.1
- [ ] Store login credentials tiliado/nuvolaplayer#41
- [ ] Non-media apps eat global media hotkeys tiliado/nuvolaplayer#230
- [x] Release 3.1.1 tiliado/nuvolaplayer#209

### Extra
- [x] Create HTTP-JSON server interface for remote control over network tiliado/nuvolaplayer#19
- [x] Watch App to control Nuvola Player over Wi-Fi tiliado/nuvolaplayer#133
