### ISSUE TITLE
Roadmap for July 2015

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#4]
## Funding
- [Fundraiser July 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201507/) yielded **€248.07**.
- There are no extra expenses (domain, hosting, etc.) planned for July 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is  248.07/10 = **24.8 hours** :+1: 
  ![image](https://cloud.githubusercontent.com/assets/853706/8545161/0b28ab6e-24ac-11e5-9f39-0bdce98a8d79.png)
## Planned Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer), but funded time is still low.
- Importance of tasks: Urgent > Code review > Bugs > Features requested by Patrons >> Other feature requests
- Milestone July 2015:
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/July%202015)
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/July%202015)
### Urgent
- [x] Write CONTRIBUTE.md (tiliado/nuvolaplayer#114) :construction_worker: ~~1 hour~~ 0.77 hours :+1:
- [x]  Create new template for web app scripts (tiliado/nuvolaplayer#119) :construction_worker: 2 hour
- [x] Linux Mint doesn't install nuvolaplayer3-all-services by default -  tiliado/nuvolaplayer#107 :construction_worker: ~~1 hour~~ 0.79 h :+1: 
- [x] Spotify only shows the Spotify's logo on a black background - tiliado/nuvolaplayer#82 :construction_worker: 2 hours
- [x] Prepare packages for Debian 9 Stretch (testing) (tiliado/nuvolaplayer#96) :construction_worker: 2 hour max, postpone otherwise
### Important
- [x]  Code review and packaging: TuneIn Radio (tiliado/nuvolaplayer#43) :construction_worker: 1 hour - waiting for repo transfer
- [x] Code review: SoundCloud - AltarBeastiful/nuvola-app-soundcloud#1 :construction_worker: 2 hours - still some issues
- [x] Code review: Logitech Media Server - tiliado/nuvola-app-logitech-media-server#1 :construction_worker: 2 hours
- [x] Code Review: Amazon Cloud Player script - tiliado/nuvola-app-amazon-cloud-player#2 :construction_worker: 2 hours - still some issues
- [ ] Service Request: 8tracks (tiliado/nuvolaplayer#77) :construction_worker: 3 hours
- [x]  Code Review: Plex tiliado/nuvolaplayer#125 
### Other
- [x] Smarter Client side decoration detection (tiliado/diorite#2) :construction_worker: ~~2 hours max~~ 5.71 hours, I didn't want to left it unfinished
- [x]  Fails to build under non-UTF-8 locale (UnicodeDecodeError in nuvolamergejs.py) tiliado/nuvolaplayer#123  :construction_worker: 1 hour
- [x]  Enable Headerbar in Pantheon/Freya tiliado/nuvolaplayer#108  :construction_worker: 0.5 hour
- [x] Also scrobble album to last.fm (tiliado/nuvolaplayer#73):  Easy to fix. :construction_worker: 15 min
- [x]  Last.fm scrobbling fails and gets disabled (Your request timed out.) tiliado/nuvolaplayer#115 :construction_worker: 1 hour
- [x] Warn user when global keybinding fails and provide help (tiliado/nuvolaplayer#93): Easy to fix. :construction_worker: 30 min
- [ ] Google Play Music shows an incomplete queue (tiliado/nuvolaplayer#106) :construction_worker: 2 hours max, postpone otherwise

**Comment by jiri-janousek** [comment]
Closing as funds have been spent. See #5 for next month.
