### ISSUE TITLE
Roadmap for November 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#42]
Roadmaps: [October 2016](https://github.com/tiliado/nuvolaplayer.project/issues/39) • **November 2016** • [December 2016](https://github.com/tiliado/nuvolaplayer.project/issues/43)

## Funding

- [Fundraiser November 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201611/)  yielded **€131.1**.
- €125.1 remains after an advance of **€6** on **tiliado.eu domain & hosting**.
- Funded time is 125.1/15 = **8.34 hours**
- Threshold **40 hours** for revenue sharing with contributors wasn't reached. 

## Milestones
- [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestone/28)
- [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestone/16)

## Proposed Tasks

- [x] More robust fetching of album art: Allow to use actual image data instead of image URL tiliado/nuvolaplayer#76
- [x] Fix repeated Runner: prefix in debugging output tiliado/nuvolaplayer#265
- [x] Too many flash plugins - false positive tiliado/nuvolaplayer#159
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204
- [ ] Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2 - including MPRIS rating
- [ ] Store login credentials tiliado/nuvolaplayer#41 - password manager
- [ ] Add Unity AppIndicator tiliado/nuvolaplayer#45
- [ ] Fix all critical warnings tiliado/nuvolaplayer#247
- [ ] Nuvolaplayer is deleting and recreating .desktop file on every launch tiliado/nuvolaplayer#248
- [ ] Introduce Nuvola SDK tiliado/nuvolaplayer#269
- [ ] Web App scripts should provide desktop file tiliado/nuvolaplayer#263
- [ ] Non-media apps eat global media hotkeys tiliado/nuvolaplayer#230

## New Services

If funding gets over 15 hours, let's add at least one new script.
- [ ] Service request: Pocket Casts tiliado/nuvolaplayer#186
- [ ] Service request: Mentor FM tiliado/nuvolaplayer#151
- [ ] Service Request: Goear tiliado/nuvolaplayer#130

## Watchlist

- [ ] Today google music has a new interface tiliado/nuvolaplayer#271
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 - developer documentation & Is there new release at the GNOME Shell Extensions website?

**Comment by jiri-janousek** [comment]
Out of funds.
