### ISSUE TITLE
Roadmap for December 2016

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#43]
Roadmaps: [November 2016](https://github.com/tiliado/nuvolaplayer.project/issues/42) • **December 2016** • [January 2017](https://github.com/tiliado/nuvolaplayer.project/issues/44)

## Funding

[Fundraiser December 2016](https://tiliado.eu/nuvolaplayer/funding/tasks/201612/) is in progress.

## Proposed Tasks

- [ ] Add Unity AppIndicator tiliado/nuvolaplayer#45
- [x] Release 3.0.5 tiliado/nuvolaplayer#275
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204
- [ ] Yandex Music: feauture request like button shortcut tiliado/nuvola-app-yandex-music#2 - including MPRIS rating
- [ ] Store login credentials tiliado/nuvolaplayer#41 - password manager
- [ ] Fix all critical warnings tiliado/nuvolaplayer#247
- [x] Nuvolaplayer is deleting and recreating .desktop file on every launch tiliado/nuvolaplayer#248
- [x] Introduce Nuvola SDK tiliado/nuvolaplayer#269
- [ ] Web App scripts should provide desktop file tiliado/nuvolaplayer#263
- [ ] Non-media apps eat global media hotkeys tiliado/nuvolaplayer#230

## New Services

If funding gets over 15 hours, let's add at least one new script.
- [ ] Pocket Casts tiliado/nuvolaplayer#186
- [ ] Mentor FM tiliado/nuvolaplayer#151
- [ ] Goear tiliado/nuvolaplayer#130
- [ ] Focus@Will tiliado/nuvolaplayer#44

## Watchlist

- [ ] Today google music has a new interface tiliado/nuvolaplayer#271
- [ ] Add MPRIS thumbs up/down actions tiliado/nuvolaplayer#204 - developer documentation & Is there new release at the GNOME Shell Extensions website?
