### ISSUE TITLE
Roadmap for February 2017

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#46]
Proposed tasks
-------------------

### Critical

* [x] Huge CPU Usage tiliado/nuvolaplayer#260
* [x] Frequent apprunner deadlocks in 3.1 on Stretch since ~2016-12-12 tiliado/nuvolaplayer#279
* [ ] Amazon music/Spotify stops/crashes playback on Ubuntu 16.04 using Gnome-Shell tiliado/nuvolaplayer#278
* [x] Create Nuvola CDK with MSE turned on tiliado/nuvolaplayer#288
* [ ] Examine HTML5 Audio support in Google Play tiliado/nuvolaplayer#91
* [x] Fix all critical warnings tiliado/nuvolaplayer#247
