### ISSUE TITLE
Roadmap for August 2015

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#5]
Previous month #4 • Next month #7 
## Funding
- [Fundraiser August 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201508/) yielded **€263.46**.
- There are no extra expenses (domain, hosting, etc.) planned for August 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is  263.46/10 = **26.3 hours** :+1: 

![image](https://cloud.githubusercontent.com/assets/853706/9081604/21dc5ea0-3b5e-11e5-8511-d279100f6b89.png)
## Planned Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Importance of tasks: Urgent > Code review > Bugs > Features requested by Patrons >> ~~Other feature requests~~ (no time for that)
- Milestone August 2015
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/August%202015)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/August%202015)
### Urgent
- [x] Spotify Ads louder than actual songs tiliado/nuvola-app-spotify#6
- [x] Rdio: System master volume reset to 100% after track switch tiliado/nuvola-app-rdio#2 
- [x] Crash after "Failed to open BO for returned DRI2 buffer" tiliado/nuvolaplayer#131
- [x] Google Play Music shows an incomplete queue (tiliado/nuvolaplayer#106)
- [x] Prepare packages for Fedora 22 tiliado/nuvolaplayer#99
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128
### Important
- [x]  TuneIn Radio tiliado/nuvolaplayer#43 - packaging
- [x]  Plex music tiliado/nuvolaplayer#125  - packaging
- [x] Amazon Cloud Player tiliado/nuvolaplayer#75 - packaging
- [x]  Add lyrics fetching tiliado/nuvolaplayer#13
- [x] Code review: SoundCloud - tiliado/nuvolaplayer#30 - deadline August 14
- [x] Service Request: 8tracks tiliado/nuvolaplayer#77
- [x] Service request: Yandex.Music tiliado/nuvolaplayer#31
### Other
- [x] Close to tray inconsistent behaviour tiliado/nuvolaplayer#89
- [ ] Update screenshots and social network artwork tiliado/nuvolaplayer.project#10 
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Wrong enabled/disabled state of actions in nuvolaplayer3ctl tiliado/nuvolaplayer#112
- [ ] Change name of MPRIS interface tiliado/nuvolaplayer#120
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Use jslint for web app scripts tiliado/nuvolaplayer#132 
- [ ] Update Service Integration Guidelines tiliado/nuvolaplayer#127 
- [ ] Media player extension also says that Google Play "stops" very briefly whenever I skip a song tiliado/nuvolaplayer#118
- [ ] MPRIS interface doesn't block disabled actions (e.g. play) tiliado/nuvolaplayer#136

**Comment by jiri-janousek** [comment]
Out of funds, closing. Next month: #7
