### ISSUE TITLE
Roadmap for September 2015

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#7]
## Funding
- [Fundraiser September 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201509/) yielded **€268.13**.
- There are no extra expenses (domain, hosting, etc.) planned for September 2015.
- Threshold €400 for revenue sharing with contributors wasn't reached :-1: 
- Funded time is  268.13/11 = **24.3 hours** :+1: (I've increased my reward by €1 as I have less spare time.)
## Proposed Tasks
- [List of tasks is pretty full](https://waffle.io/tiliado/nuvolaplayer).
- Importance of tasks: Urgent > Code review > Bugs > Features requested by Patrons >> ~~Other feature requests~~ (no time for that)
- Milestone September 2015
  - [tiliado/nuvolaplayer.project](https://github.com/tiliado/nuvolaplayer.project/milestones/September%202015)
  - [tiliado/nuvolaplayer](https://github.com/tiliado/nuvolaplayer/milestones/September%202015)
### Urgent
- [x]  Images fail to load due to Invalid 'blob' protocol tiliado/nuvolaplayer#145 
- [ ] When clicking the play button next to a song on the artist panel, window shifts out tiliado/nuvola-app-spotify#7 - It is necessary to reproduce the issue in the jhbuild of the WebKitGTK and forward it upstream.
- [ ]  Google Play Music fails to stream from radio (All Access), but uploaded songs do work tiliado/nuvolaplayer#124 - debug output deadline September 26
- [x]  Google Play Music update breaks Nuvola tiliado/nuvolaplayer#100 
- [x]  Fix size and overflow of preferences dialog tiliado/nuvolaplayer#140
- [ ] Can't login to Rdio via Facebook tiliado/nuvola-app-rdio#4 - waiting for a response from service maintainer 
- [ ]  Update Nuvola Player 3 relese notes tiliado/nuvolaplayer.project#11 
- [ ]  Google Play Music is not working in Ubuntu 14.04: freeze in the middle of loading tiliado/nuvolaplayer#134 - waiting for response, javascript error, try in virtualbox
- [ ] Create CONTRIBUTING.md for web app scripts tiliado/nuvolaplayer#128
- [ ] Update Service Integration Guidelines tiliado/nuvolaplayer#127 
- [ ] Wrong enabled/disabled state of actions in nuvolaplayer3ctl tiliado/nuvolaplayer#112
- [ ] MPRIS interface doesn't block disabled actions (e.g. play) tiliado/nuvolaplayer#136
- [x] Synchronise stream volume with app volume tiliado/nuvola-app-rdio#3 - merge and make a new release
- [ ] Google Play Music might not work with Labs Notifications enabled tiliado/nuvolaplayer#150
- [ ] Check HTML5 Audio support in streaming services and disable Flash #158 (GFM: tiliado/nuvolaplayer#158
### Important
- [ ] Service Request: Youtube tiliado/nuvolaplayer#83 - code review
- [ ]  Service Request: Microsoft Groove tiliado/nuvolaplayer#149 - code review
- [ ] Service request: RuneAudio  tiliado/nuvolaplayer#154  - code review
- [ ] Set default player window width from metadata.json tiliado/nuvolaplayer#141
- [ ]  Apply URL sandbox also for window.open() tiliado/nuvolaplayer#142
- [ ]  Service request: Youradio tiliado/nuvolaplayer#153  - code review
- [ ] Service Request: Ampache/Owncloud [$25] tiliado/nuvolaplayer#52
- [ ] Add translations tiliado/nuvolaplayer#10
- [ ] Create welcome wizard tiliado/nuvolaplayer#18
### Other
- [ ] Update screenshots and social network artwork tiliado/nuvolaplayer.project#10 
- [ ] Add multiple icons like in Google Calendar script tiliado/nuvolaplayer#126
- [ ] Change name of MPRIS interface tiliado/nuvolaplayer#120
- [ ] Use jslint for web app scripts tiliado/nuvolaplayer#132 
- [ ] Show donate bar based on 0.5 hour ticks tiliado/nuvolaplayer#122 
- [ ] Change name of MPRIS interface tiliado/nuvolaplayer#120
- [ ] Media player extension also says that Google Play "stops" very briefly whenever I skip a song tiliado/nuvolaplayer#118

**Comment by jiri-janousek** [comment]
There have been some unplanned tasks done:
- [Nuvola Apps Alpha and service selector changes](https://tiliado.eu/nuvolaplayer/funding/task/90/)
- [Pkgapps2.py script](https://tiliado.eu/nuvolaplayer/funding/task/92/)
- [Packages for Ubuntu 15.10 Wily Werewolf (in progress)](https://tiliado.eu/nuvolaplayer/funding/task/93/)

**Comment by jiri-janousek** [comment]
Out of funds, next month #13
